/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Dynamic_Bicycle_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[3] = {0, 0, 0};

/* Dynamic_Bicycle_expl_ode_fun:(i0[7],i1,i2[])->(o0[7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7;
  /* #0: @0 = input[0][5] */
  w0 = arg[0] ? arg[0][5] : 0;
  /* #1: @1 = cos(@0) */
  w1 = cos( w0 );
  /* #2: @1 = (2.*@1) */
  w1 = (2.* w1 );
  /* #3: @2 = input[0][4] */
  w2 = arg[0] ? arg[0][4] : 0;
  /* #4: @3 = sin(@0) */
  w3 = sin( w0 );
  /* #5: @3 = (@2*@3) */
  w3  = (w2*w3);
  /* #6: @1 = (@1-@3) */
  w1 -= w3;
  /* #7: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #8: @1 = sin(@0) */
  w1 = sin( w0 );
  /* #9: @1 = (2.*@1) */
  w1 = (2.* w1 );
  /* #10: @0 = cos(@0) */
  w0 = cos( w0 );
  /* #11: @0 = (@2*@0) */
  w0  = (w2*w0);
  /* #12: @1 = (@1+@0) */
  w1 += w0;
  /* #13: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #14: @1 = 2 */
  w1 = 2.;
  /* #15: output[0][2] = @1 */
  if (res[0]) res[0][2] = w1;
  /* #16: output[0][3] = @2 */
  if (res[0]) res[0][3] = w2;
  /* #17: @1 = -2 */
  w1 = -2.;
  /* #18: @0 = input[0][6] */
  w0 = arg[0] ? arg[0][6] : 0;
  /* #19: @1 = (@1*@0) */
  w1 *= w0;
  /* #20: @3 = 0.359195 */
  w3 = 3.5919540229885061e-01;
  /* #21: @4 = -6.932 */
  w4 = -6.9320000000000004e+00;
  /* #22: @5 = 0.205 */
  w5 = 2.0499999999999999e-01;
  /* #23: @5 = (@5*@0) */
  w5 *= w0;
  /* #24: @5 = (@2+@5) */
  w5  = (w2+w5);
  /* #25: @6 = 2 */
  w6 = 2.;
  /* #26: @5 = atan2(@5,@6) */
  w5  = atan2(w5,w6);
  /* #27: @6 = input[1][0] */
  w6 = arg[1] ? arg[1][0] : 0;
  /* #28: @5 = (@5-@6) */
  w5 -= w6;
  /* #29: @4 = (@4*@5) */
  w4 *= w5;
  /* #30: @6 = cos(@6) */
  w6 = cos( w6 );
  /* #31: @6 = (@4*@6) */
  w6  = (w4*w6);
  /* #32: @5 = -6.918 */
  w5 = -6.9180000000000001e+00;
  /* #33: @7 = 0.199 */
  w7 = 1.9900000000000001e-01;
  /* #34: @7 = (@7*@0) */
  w7 *= w0;
  /* #35: @2 = (@2-@7) */
  w2 -= w7;
  /* #36: @7 = 2 */
  w7 = 2.;
  /* #37: @2 = atan2(@2,@7) */
  w2  = atan2(w2,w7);
  /* #38: @5 = (@5*@2) */
  w5 *= w2;
  /* #39: @6 = (@6+@5) */
  w6 += w5;
  /* #40: @3 = (@3*@6) */
  w3 *= w6;
  /* #41: @1 = (@1+@3) */
  w1 += w3;
  /* #42: output[0][4] = @1 */
  if (res[0]) res[0][4] = w1;
  /* #43: output[0][5] = @0 */
  if (res[0]) res[0][5] = w0;
  /* #44: @0 = 11.976 */
  w0 = 1.1976047904191615e+01;
  /* #45: @1 = 0.205 */
  w1 = 2.0499999999999999e-01;
  /* #46: @1 = (@1*@4) */
  w1 *= w4;
  /* #47: @4 = 0.199 */
  w4 = 1.9900000000000001e-01;
  /* #48: @4 = (@4*@5) */
  w4 *= w5;
  /* #49: @1 = (@1-@4) */
  w1 -= w4;
  /* #50: @0 = (@0*@1) */
  w0 *= w1;
  /* #51: output[0][6] = @0 */
  if (res[0]) res[0][6] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int Dynamic_Bicycle_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Dynamic_Bicycle_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Dynamic_Bicycle_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Dynamic_Bicycle_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Dynamic_Bicycle_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Dynamic_Bicycle_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Dynamic_Bicycle_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Dynamic_Bicycle_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Dynamic_Bicycle_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int Dynamic_Bicycle_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Dynamic_Bicycle_expl_ode_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Dynamic_Bicycle_expl_ode_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Dynamic_Bicycle_expl_ode_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Dynamic_Bicycle_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Dynamic_Bicycle_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Dynamic_Bicycle_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 8;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
