/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Dynamic_Bicycle_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

static const casadi_int casadi_s0[6] = {7, 1, 0, 2, 4, 6};
static const casadi_int casadi_s1[10] = {7, 1, 0, 6, 0, 1, 3, 4, 5, 6};
static const casadi_int casadi_s2[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s3[59] = {7, 7, 0, 7, 14, 21, 28, 35, 42, 49, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s5[3] = {0, 0, 0};
static const casadi_int casadi_s6[52] = {7, 7, 0, 6, 12, 18, 24, 30, 36, 42, 0, 1, 3, 4, 5, 6, 0, 1, 3, 4, 5, 6, 0, 1, 3, 4, 5, 6, 0, 1, 3, 4, 5, 6, 0, 1, 3, 4, 5, 6, 0, 1, 3, 4, 5, 6, 0, 1, 3, 4, 5, 6};

/* Dynamic_Bicycle_expl_vde_forw:(i0[7],i1[7x7],i2[7],i3,i4[])->(o0[7],o1[7x7,42nz],o2[7x1,6nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, *w21=w+28, *w22=w+77, *w23=w+84, *w24=w+91, *w25=w+98, *w26=w+105, *w27=w+112, *w28=w+119, w29, w30, w31, w32, w33, w34, w35, w36, w37, *w38=w+135, *w44=w+137, *w45=w+139, *w46=w+141, *w47=w+147;
  /* #0: @0 = input[0][5] */
  w0 = arg[0] ? arg[0][5] : 0;
  /* #1: @1 = cos(@0) */
  w1 = cos( w0 );
  /* #2: @2 = input[0][4] */
  w2 = arg[0] ? arg[0][4] : 0;
  /* #3: @3 = sin(@0) */
  w3 = sin( w0 );
  /* #4: @4 = (@2*@3) */
  w4  = (w2*w3);
  /* #5: @1 = (@1-@4) */
  w1 -= w4;
  /* #6: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #7: @1 = sin(@0) */
  w1 = sin( w0 );
  /* #8: @4 = cos(@0) */
  w4 = cos( w0 );
  /* #9: @5 = (@2*@4) */
  w5  = (w2*w4);
  /* #10: @1 = (@1+@5) */
  w1 += w5;
  /* #11: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #12: @1 = 1 */
  w1 = 1.;
  /* #13: output[0][2] = @1 */
  if (res[0]) res[0][2] = w1;
  /* #14: output[0][3] = @2 */
  if (res[0]) res[0][3] = w2;
  /* #15: @1 = 0.359195 */
  w1 = 3.5919540229885061e-01;
  /* #16: @5 = -6.932 */
  w5 = -6.9320000000000004e+00;
  /* #17: @6 = 0.205 */
  w6 = 2.0499999999999999e-01;
  /* #18: @7 = input[0][6] */
  w7 = arg[0] ? arg[0][6] : 0;
  /* #19: @8 = (@6*@7) */
  w8  = (w6*w7);
  /* #20: @8 = (@2+@8) */
  w8  = (w2+w8);
  /* #21: @9 = 1 */
  w9 = 1.;
  /* #22: @10 = atan2(@8,@9) */
  w10  = atan2(w8,w9);
  /* #23: @11 = input[3][0] */
  w11 = arg[3] ? arg[3][0] : 0;
  /* #24: @10 = (@10-@11) */
  w10 -= w11;
  /* #25: @10 = (@5*@10) */
  w10  = (w5*w10);
  /* #26: @12 = cos(@11) */
  w12 = cos( w11 );
  /* #27: @13 = (@10*@12) */
  w13  = (w10*w12);
  /* #28: @14 = -6.918 */
  w14 = -6.9180000000000001e+00;
  /* #29: @15 = 0.199 */
  w15 = 1.9900000000000001e-01;
  /* #30: @16 = (@15*@7) */
  w16  = (w15*w7);
  /* #31: @16 = (@2-@16) */
  w16  = (w2-w16);
  /* #32: @17 = 1 */
  w17 = 1.;
  /* #33: @18 = atan2(@16,@17) */
  w18  = atan2(w16,w17);
  /* #34: @18 = (@14*@18) */
  w18  = (w14*w18);
  /* #35: @13 = (@13+@18) */
  w13 += w18;
  /* #36: @13 = (@1*@13) */
  w13  = (w1*w13);
  /* #37: @13 = (@13-@7) */
  w13 -= w7;
  /* #38: output[0][4] = @13 */
  if (res[0]) res[0][4] = w13;
  /* #39: output[0][5] = @7 */
  if (res[0]) res[0][5] = w7;
  /* #40: @7 = 11.976 */
  w7 = 1.1976047904191615e+01;
  /* #41: @13 = 0.205 */
  w13 = 2.0499999999999999e-01;
  /* #42: @19 = (@13*@10) */
  w19  = (w13*w10);
  /* #43: @20 = 0.199 */
  w20 = 1.9900000000000001e-01;
  /* #44: @18 = (@20*@18) */
  w18  = (w20*w18);
  /* #45: @19 = (@19-@18) */
  w19 -= w18;
  /* #46: @19 = (@7*@19) */
  w19  = (w7*w19);
  /* #47: output[0][6] = @19 */
  if (res[0]) res[0][6] = w19;
  /* #48: @21 = input[1][0] */
  casadi_copy(arg[1], 49, w21);
  /* #49: {@22, @23, @24, @25, @26, @27, @28} = horzsplit(@21) */
  casadi_copy(w21, 7, w22);
  casadi_copy(w21+7, 7, w23);
  casadi_copy(w21+14, 7, w24);
  casadi_copy(w21+21, 7, w25);
  casadi_copy(w21+28, 7, w26);
  casadi_copy(w21+35, 7, w27);
  casadi_copy(w21+42, 7, w28);
  /* #50: {NULL, NULL, NULL, NULL, @19, @18, @29} = vertsplit(@22) */
  w19 = w22[4];
  w18 = w22[5];
  w29 = w22[6];
  /* #51: @30 = (@3*@19) */
  w30  = (w3*w19);
  /* #52: @31 = cos(@0) */
  w31 = cos( w0 );
  /* #53: @32 = (@31*@18) */
  w32  = (w31*w18);
  /* #54: @32 = (@2*@32) */
  w32  = (w2*w32);
  /* #55: @30 = (@30+@32) */
  w30 += w32;
  /* #56: @30 = (-@30) */
  w30 = (- w30 );
  /* #57: @32 = sin(@0) */
  w32 = sin( w0 );
  /* #58: @33 = (@32*@18) */
  w33  = (w32*w18);
  /* #59: @30 = (@30-@33) */
  w30 -= w33;
  /* #60: output[1][0] = @30 */
  if (res[1]) res[1][0] = w30;
  /* #61: @30 = cos(@0) */
  w30 = cos( w0 );
  /* #62: @33 = (@30*@18) */
  w33  = (w30*w18);
  /* #63: @34 = (@4*@19) */
  w34  = (w4*w19);
  /* #64: @35 = sin(@0) */
  w35 = sin( w0 );
  /* #65: @18 = (@35*@18) */
  w18  = (w35*w18);
  /* #66: @18 = (@2*@18) */
  w18  = (w2*w18);
  /* #67: @34 = (@34-@18) */
  w34 -= w18;
  /* #68: @33 = (@33+@34) */
  w33 += w34;
  /* #69: output[1][1] = @33 */
  if (res[1]) res[1][1] = w33;
  /* #70: output[1][2] = @19 */
  if (res[1]) res[1][2] = w19;
  /* #71: @33 = (@6*@29) */
  w33  = (w6*w29);
  /* #72: @33 = (@19+@33) */
  w33  = (w19+w33);
  /* #73: @34 = sq(@8) */
  w34 = casadi_sq( w8 );
  /* #74: @34 = (@9+@34) */
  w34  = (w9+w34);
  /* #75: @33 = (@33/@34) */
  w33 /= w34;
  /* #76: @33 = (@5*@33) */
  w33  = (w5*w33);
  /* #77: @18 = (@12*@33) */
  w18  = (w12*w33);
  /* #78: @36 = (@15*@29) */
  w36  = (w15*w29);
  /* #79: @19 = (@19-@36) */
  w19 -= w36;
  /* #80: @36 = sq(@16) */
  w36 = casadi_sq( w16 );
  /* #81: @36 = (@17+@36) */
  w36  = (w17+w36);
  /* #82: @19 = (@19/@36) */
  w19 /= w36;
  /* #83: @19 = (@14*@19) */
  w19  = (w14*w19);
  /* #84: @18 = (@18+@19) */
  w18 += w19;
  /* #85: @18 = (@1*@18) */
  w18  = (w1*w18);
  /* #86: @18 = (@18-@29) */
  w18 -= w29;
  /* #87: output[1][3] = @18 */
  if (res[1]) res[1][3] = w18;
  /* #88: output[1][4] = @29 */
  if (res[1]) res[1][4] = w29;
  /* #89: @33 = (@13*@33) */
  w33  = (w13*w33);
  /* #90: @19 = (@20*@19) */
  w19  = (w20*w19);
  /* #91: @33 = (@33-@19) */
  w33 -= w19;
  /* #92: @33 = (@7*@33) */
  w33  = (w7*w33);
  /* #93: output[1][5] = @33 */
  if (res[1]) res[1][5] = w33;
  /* #94: {NULL, NULL, NULL, NULL, @33, @19, @29} = vertsplit(@23) */
  w33 = w23[4];
  w19 = w23[5];
  w29 = w23[6];
  /* #95: @18 = (@3*@33) */
  w18  = (w3*w33);
  /* #96: @37 = (@31*@19) */
  w37  = (w31*w19);
  /* #97: @37 = (@2*@37) */
  w37  = (w2*w37);
  /* #98: @18 = (@18+@37) */
  w18 += w37;
  /* #99: @18 = (-@18) */
  w18 = (- w18 );
  /* #100: @37 = (@32*@19) */
  w37  = (w32*w19);
  /* #101: @18 = (@18-@37) */
  w18 -= w37;
  /* #102: output[1][6] = @18 */
  if (res[1]) res[1][6] = w18;
  /* #103: @18 = (@30*@19) */
  w18  = (w30*w19);
  /* #104: @37 = (@4*@33) */
  w37  = (w4*w33);
  /* #105: @19 = (@35*@19) */
  w19  = (w35*w19);
  /* #106: @19 = (@2*@19) */
  w19  = (w2*w19);
  /* #107: @37 = (@37-@19) */
  w37 -= w19;
  /* #108: @18 = (@18+@37) */
  w18 += w37;
  /* #109: output[1][7] = @18 */
  if (res[1]) res[1][7] = w18;
  /* #110: output[1][8] = @33 */
  if (res[1]) res[1][8] = w33;
  /* #111: @18 = (@6*@29) */
  w18  = (w6*w29);
  /* #112: @18 = (@33+@18) */
  w18  = (w33+w18);
  /* #113: @18 = (@18/@34) */
  w18 /= w34;
  /* #114: @18 = (@5*@18) */
  w18  = (w5*w18);
  /* #115: @37 = (@12*@18) */
  w37  = (w12*w18);
  /* #116: @19 = (@15*@29) */
  w19  = (w15*w29);
  /* #117: @33 = (@33-@19) */
  w33 -= w19;
  /* #118: @33 = (@33/@36) */
  w33 /= w36;
  /* #119: @33 = (@14*@33) */
  w33  = (w14*w33);
  /* #120: @37 = (@37+@33) */
  w37 += w33;
  /* #121: @37 = (@1*@37) */
  w37  = (w1*w37);
  /* #122: @37 = (@37-@29) */
  w37 -= w29;
  /* #123: output[1][9] = @37 */
  if (res[1]) res[1][9] = w37;
  /* #124: output[1][10] = @29 */
  if (res[1]) res[1][10] = w29;
  /* #125: @18 = (@13*@18) */
  w18  = (w13*w18);
  /* #126: @33 = (@20*@33) */
  w33  = (w20*w33);
  /* #127: @18 = (@18-@33) */
  w18 -= w33;
  /* #128: @18 = (@7*@18) */
  w18  = (w7*w18);
  /* #129: output[1][11] = @18 */
  if (res[1]) res[1][11] = w18;
  /* #130: {NULL, NULL, NULL, NULL, @18, @33, @29} = vertsplit(@24) */
  w18 = w24[4];
  w33 = w24[5];
  w29 = w24[6];
  /* #131: @37 = (@3*@18) */
  w37  = (w3*w18);
  /* #132: @19 = (@31*@33) */
  w19  = (w31*w33);
  /* #133: @19 = (@2*@19) */
  w19  = (w2*w19);
  /* #134: @37 = (@37+@19) */
  w37 += w19;
  /* #135: @37 = (-@37) */
  w37 = (- w37 );
  /* #136: @19 = (@32*@33) */
  w19  = (w32*w33);
  /* #137: @37 = (@37-@19) */
  w37 -= w19;
  /* #138: output[1][12] = @37 */
  if (res[1]) res[1][12] = w37;
  /* #139: @37 = (@30*@33) */
  w37  = (w30*w33);
  /* #140: @19 = (@4*@18) */
  w19  = (w4*w18);
  /* #141: @33 = (@35*@33) */
  w33  = (w35*w33);
  /* #142: @33 = (@2*@33) */
  w33  = (w2*w33);
  /* #143: @19 = (@19-@33) */
  w19 -= w33;
  /* #144: @37 = (@37+@19) */
  w37 += w19;
  /* #145: output[1][13] = @37 */
  if (res[1]) res[1][13] = w37;
  /* #146: output[1][14] = @18 */
  if (res[1]) res[1][14] = w18;
  /* #147: @37 = (@6*@29) */
  w37  = (w6*w29);
  /* #148: @37 = (@18+@37) */
  w37  = (w18+w37);
  /* #149: @37 = (@37/@34) */
  w37 /= w34;
  /* #150: @37 = (@5*@37) */
  w37  = (w5*w37);
  /* #151: @19 = (@12*@37) */
  w19  = (w12*w37);
  /* #152: @33 = (@15*@29) */
  w33  = (w15*w29);
  /* #153: @18 = (@18-@33) */
  w18 -= w33;
  /* #154: @18 = (@18/@36) */
  w18 /= w36;
  /* #155: @18 = (@14*@18) */
  w18  = (w14*w18);
  /* #156: @19 = (@19+@18) */
  w19 += w18;
  /* #157: @19 = (@1*@19) */
  w19  = (w1*w19);
  /* #158: @19 = (@19-@29) */
  w19 -= w29;
  /* #159: output[1][15] = @19 */
  if (res[1]) res[1][15] = w19;
  /* #160: output[1][16] = @29 */
  if (res[1]) res[1][16] = w29;
  /* #161: @37 = (@13*@37) */
  w37  = (w13*w37);
  /* #162: @18 = (@20*@18) */
  w18  = (w20*w18);
  /* #163: @37 = (@37-@18) */
  w37 -= w18;
  /* #164: @37 = (@7*@37) */
  w37  = (w7*w37);
  /* #165: output[1][17] = @37 */
  if (res[1]) res[1][17] = w37;
  /* #166: {NULL, NULL, NULL, NULL, @37, @18, @29} = vertsplit(@25) */
  w37 = w25[4];
  w18 = w25[5];
  w29 = w25[6];
  /* #167: @19 = (@3*@37) */
  w19  = (w3*w37);
  /* #168: @33 = (@31*@18) */
  w33  = (w31*w18);
  /* #169: @33 = (@2*@33) */
  w33  = (w2*w33);
  /* #170: @19 = (@19+@33) */
  w19 += w33;
  /* #171: @19 = (-@19) */
  w19 = (- w19 );
  /* #172: @33 = (@32*@18) */
  w33  = (w32*w18);
  /* #173: @19 = (@19-@33) */
  w19 -= w33;
  /* #174: output[1][18] = @19 */
  if (res[1]) res[1][18] = w19;
  /* #175: @19 = (@30*@18) */
  w19  = (w30*w18);
  /* #176: @33 = (@4*@37) */
  w33  = (w4*w37);
  /* #177: @18 = (@35*@18) */
  w18  = (w35*w18);
  /* #178: @18 = (@2*@18) */
  w18  = (w2*w18);
  /* #179: @33 = (@33-@18) */
  w33 -= w18;
  /* #180: @19 = (@19+@33) */
  w19 += w33;
  /* #181: output[1][19] = @19 */
  if (res[1]) res[1][19] = w19;
  /* #182: output[1][20] = @37 */
  if (res[1]) res[1][20] = w37;
  /* #183: @19 = (@6*@29) */
  w19  = (w6*w29);
  /* #184: @19 = (@37+@19) */
  w19  = (w37+w19);
  /* #185: @19 = (@19/@34) */
  w19 /= w34;
  /* #186: @19 = (@5*@19) */
  w19  = (w5*w19);
  /* #187: @33 = (@12*@19) */
  w33  = (w12*w19);
  /* #188: @18 = (@15*@29) */
  w18  = (w15*w29);
  /* #189: @37 = (@37-@18) */
  w37 -= w18;
  /* #190: @37 = (@37/@36) */
  w37 /= w36;
  /* #191: @37 = (@14*@37) */
  w37  = (w14*w37);
  /* #192: @33 = (@33+@37) */
  w33 += w37;
  /* #193: @33 = (@1*@33) */
  w33  = (w1*w33);
  /* #194: @33 = (@33-@29) */
  w33 -= w29;
  /* #195: output[1][21] = @33 */
  if (res[1]) res[1][21] = w33;
  /* #196: output[1][22] = @29 */
  if (res[1]) res[1][22] = w29;
  /* #197: @19 = (@13*@19) */
  w19  = (w13*w19);
  /* #198: @37 = (@20*@37) */
  w37  = (w20*w37);
  /* #199: @19 = (@19-@37) */
  w19 -= w37;
  /* #200: @19 = (@7*@19) */
  w19  = (w7*w19);
  /* #201: output[1][23] = @19 */
  if (res[1]) res[1][23] = w19;
  /* #202: {NULL, NULL, NULL, NULL, @19, @37, @29} = vertsplit(@26) */
  w19 = w26[4];
  w37 = w26[5];
  w29 = w26[6];
  /* #203: @33 = (@3*@19) */
  w33  = (w3*w19);
  /* #204: @18 = (@31*@37) */
  w18  = (w31*w37);
  /* #205: @18 = (@2*@18) */
  w18  = (w2*w18);
  /* #206: @33 = (@33+@18) */
  w33 += w18;
  /* #207: @33 = (-@33) */
  w33 = (- w33 );
  /* #208: @18 = (@32*@37) */
  w18  = (w32*w37);
  /* #209: @33 = (@33-@18) */
  w33 -= w18;
  /* #210: output[1][24] = @33 */
  if (res[1]) res[1][24] = w33;
  /* #211: @33 = (@30*@37) */
  w33  = (w30*w37);
  /* #212: @18 = (@4*@19) */
  w18  = (w4*w19);
  /* #213: @37 = (@35*@37) */
  w37  = (w35*w37);
  /* #214: @37 = (@2*@37) */
  w37  = (w2*w37);
  /* #215: @18 = (@18-@37) */
  w18 -= w37;
  /* #216: @33 = (@33+@18) */
  w33 += w18;
  /* #217: output[1][25] = @33 */
  if (res[1]) res[1][25] = w33;
  /* #218: output[1][26] = @19 */
  if (res[1]) res[1][26] = w19;
  /* #219: @33 = (@6*@29) */
  w33  = (w6*w29);
  /* #220: @33 = (@19+@33) */
  w33  = (w19+w33);
  /* #221: @33 = (@33/@34) */
  w33 /= w34;
  /* #222: @33 = (@5*@33) */
  w33  = (w5*w33);
  /* #223: @18 = (@12*@33) */
  w18  = (w12*w33);
  /* #224: @37 = (@15*@29) */
  w37  = (w15*w29);
  /* #225: @19 = (@19-@37) */
  w19 -= w37;
  /* #226: @19 = (@19/@36) */
  w19 /= w36;
  /* #227: @19 = (@14*@19) */
  w19  = (w14*w19);
  /* #228: @18 = (@18+@19) */
  w18 += w19;
  /* #229: @18 = (@1*@18) */
  w18  = (w1*w18);
  /* #230: @18 = (@18-@29) */
  w18 -= w29;
  /* #231: output[1][27] = @18 */
  if (res[1]) res[1][27] = w18;
  /* #232: output[1][28] = @29 */
  if (res[1]) res[1][28] = w29;
  /* #233: @33 = (@13*@33) */
  w33  = (w13*w33);
  /* #234: @19 = (@20*@19) */
  w19  = (w20*w19);
  /* #235: @33 = (@33-@19) */
  w33 -= w19;
  /* #236: @33 = (@7*@33) */
  w33  = (w7*w33);
  /* #237: output[1][29] = @33 */
  if (res[1]) res[1][29] = w33;
  /* #238: {NULL, NULL, NULL, NULL, @33, @19, @29} = vertsplit(@27) */
  w33 = w27[4];
  w19 = w27[5];
  w29 = w27[6];
  /* #239: @18 = (@3*@33) */
  w18  = (w3*w33);
  /* #240: @37 = (@31*@19) */
  w37  = (w31*w19);
  /* #241: @37 = (@2*@37) */
  w37  = (w2*w37);
  /* #242: @18 = (@18+@37) */
  w18 += w37;
  /* #243: @18 = (-@18) */
  w18 = (- w18 );
  /* #244: @37 = (@32*@19) */
  w37  = (w32*w19);
  /* #245: @18 = (@18-@37) */
  w18 -= w37;
  /* #246: output[1][30] = @18 */
  if (res[1]) res[1][30] = w18;
  /* #247: @18 = (@30*@19) */
  w18  = (w30*w19);
  /* #248: @37 = (@4*@33) */
  w37  = (w4*w33);
  /* #249: @19 = (@35*@19) */
  w19  = (w35*w19);
  /* #250: @19 = (@2*@19) */
  w19  = (w2*w19);
  /* #251: @37 = (@37-@19) */
  w37 -= w19;
  /* #252: @18 = (@18+@37) */
  w18 += w37;
  /* #253: output[1][31] = @18 */
  if (res[1]) res[1][31] = w18;
  /* #254: output[1][32] = @33 */
  if (res[1]) res[1][32] = w33;
  /* #255: @18 = (@6*@29) */
  w18  = (w6*w29);
  /* #256: @18 = (@33+@18) */
  w18  = (w33+w18);
  /* #257: @18 = (@18/@34) */
  w18 /= w34;
  /* #258: @18 = (@5*@18) */
  w18  = (w5*w18);
  /* #259: @37 = (@12*@18) */
  w37  = (w12*w18);
  /* #260: @19 = (@15*@29) */
  w19  = (w15*w29);
  /* #261: @33 = (@33-@19) */
  w33 -= w19;
  /* #262: @33 = (@33/@36) */
  w33 /= w36;
  /* #263: @33 = (@14*@33) */
  w33  = (w14*w33);
  /* #264: @37 = (@37+@33) */
  w37 += w33;
  /* #265: @37 = (@1*@37) */
  w37  = (w1*w37);
  /* #266: @37 = (@37-@29) */
  w37 -= w29;
  /* #267: output[1][33] = @37 */
  if (res[1]) res[1][33] = w37;
  /* #268: output[1][34] = @29 */
  if (res[1]) res[1][34] = w29;
  /* #269: @18 = (@13*@18) */
  w18  = (w13*w18);
  /* #270: @33 = (@20*@33) */
  w33  = (w20*w33);
  /* #271: @18 = (@18-@33) */
  w18 -= w33;
  /* #272: @18 = (@7*@18) */
  w18  = (w7*w18);
  /* #273: output[1][35] = @18 */
  if (res[1]) res[1][35] = w18;
  /* #274: {NULL, NULL, NULL, NULL, @18, @33, @29} = vertsplit(@28) */
  w18 = w28[4];
  w33 = w28[5];
  w29 = w28[6];
  /* #275: @37 = (@3*@18) */
  w37  = (w3*w18);
  /* #276: @31 = (@31*@33) */
  w31 *= w33;
  /* #277: @31 = (@2*@31) */
  w31  = (w2*w31);
  /* #278: @37 = (@37+@31) */
  w37 += w31;
  /* #279: @37 = (-@37) */
  w37 = (- w37 );
  /* #280: @32 = (@32*@33) */
  w32 *= w33;
  /* #281: @37 = (@37-@32) */
  w37 -= w32;
  /* #282: output[1][36] = @37 */
  if (res[1]) res[1][36] = w37;
  /* #283: @30 = (@30*@33) */
  w30 *= w33;
  /* #284: @37 = (@4*@18) */
  w37  = (w4*w18);
  /* #285: @35 = (@35*@33) */
  w35 *= w33;
  /* #286: @35 = (@2*@35) */
  w35  = (w2*w35);
  /* #287: @37 = (@37-@35) */
  w37 -= w35;
  /* #288: @30 = (@30+@37) */
  w30 += w37;
  /* #289: output[1][37] = @30 */
  if (res[1]) res[1][37] = w30;
  /* #290: output[1][38] = @18 */
  if (res[1]) res[1][38] = w18;
  /* #291: @30 = (@6*@29) */
  w30  = (w6*w29);
  /* #292: @30 = (@18+@30) */
  w30  = (w18+w30);
  /* #293: @30 = (@30/@34) */
  w30 /= w34;
  /* #294: @30 = (@5*@30) */
  w30  = (w5*w30);
  /* #295: @34 = (@12*@30) */
  w34  = (w12*w30);
  /* #296: @37 = (@15*@29) */
  w37  = (w15*w29);
  /* #297: @18 = (@18-@37) */
  w18 -= w37;
  /* #298: @18 = (@18/@36) */
  w18 /= w36;
  /* #299: @18 = (@14*@18) */
  w18  = (w14*w18);
  /* #300: @34 = (@34+@18) */
  w34 += w18;
  /* #301: @34 = (@1*@34) */
  w34  = (w1*w34);
  /* #302: @34 = (@34-@29) */
  w34 -= w29;
  /* #303: output[1][39] = @34 */
  if (res[1]) res[1][39] = w34;
  /* #304: output[1][40] = @29 */
  if (res[1]) res[1][40] = w29;
  /* #305: @30 = (@13*@30) */
  w30  = (w13*w30);
  /* #306: @18 = (@20*@18) */
  w18  = (w20*w18);
  /* #307: @30 = (@30-@18) */
  w30 -= w18;
  /* #308: @30 = (@7*@30) */
  w30  = (w7*w30);
  /* #309: output[1][41] = @30 */
  if (res[1]) res[1][41] = w30;
  /* #310: @38 = zeros(1x7,2nz) */
  casadi_clear(w38, 2);
  /* #311: @39 = 00 */
  /* #312: @40 = 00 */
  /* #313: @41 = 00 */
  /* #314: @42 = 00 */
  /* #315: @30 = 6.932 */
  w30 = 6.9320000000000004e+00;
  /* #316: @30 = (@30*@12) */
  w30 *= w12;
  /* #317: @11 = sin(@11) */
  w11 = sin( w11 );
  /* #318: @10 = (@10*@11) */
  w10 *= w11;
  /* #319: @30 = (@30-@10) */
  w30 -= w10;
  /* #320: @30 = (@1*@30) */
  w30  = (w1*w30);
  /* #321: @43 = 00 */
  /* #322: @10 = 17.0187 */
  w10 = 1.7018682634730535e+01;
  /* #323: @44 = vertcat(@39, @40, @41, @42, @30, @43, @10) */
  rr=w44;
  *rr++ = w30;
  *rr++ = w10;
  /* #324: @45 = @44[:2] */
  for (rr=w45, ss=w44+0; ss!=w44+2; ss+=1) *rr++ = *ss;
  /* #325: (@38[:2] = @45) */
  for (rr=w38+0, ss=w45; rr!=w38+2; rr+=1) *rr = *ss++;
  /* #326: @38 = @38' */
  /* #327: @46 = project(@38) */
  casadi_project(w38, casadi_s0, w46, casadi_s1, w);
  /* #328: @28 = input[2][0] */
  casadi_copy(arg[2], 7, w28);
  /* #329: {NULL, NULL, NULL, NULL, @30, @10, @11} = vertsplit(@28) */
  w30 = w28[4];
  w10 = w28[5];
  w11 = w28[6];
  /* #330: @3 = (@3*@30) */
  w3 *= w30;
  /* #331: @18 = cos(@0) */
  w18 = cos( w0 );
  /* #332: @18 = (@18*@10) */
  w18 *= w10;
  /* #333: @18 = (@2*@18) */
  w18  = (w2*w18);
  /* #334: @3 = (@3+@18) */
  w3 += w18;
  /* #335: @3 = (-@3) */
  w3 = (- w3 );
  /* #336: @18 = sin(@0) */
  w18 = sin( w0 );
  /* #337: @18 = (@18*@10) */
  w18 *= w10;
  /* #338: @3 = (@3-@18) */
  w3 -= w18;
  /* #339: @18 = cos(@0) */
  w18 = cos( w0 );
  /* #340: @18 = (@18*@10) */
  w18 *= w10;
  /* #341: @4 = (@4*@30) */
  w4 *= w30;
  /* #342: @0 = sin(@0) */
  w0 = sin( w0 );
  /* #343: @0 = (@0*@10) */
  w0 *= w10;
  /* #344: @2 = (@2*@0) */
  w2 *= w0;
  /* #345: @4 = (@4-@2) */
  w4 -= w2;
  /* #346: @18 = (@18+@4) */
  w18 += w4;
  /* #347: @39 = 00 */
  /* #348: @6 = (@6*@11) */
  w6 *= w11;
  /* #349: @6 = (@30+@6) */
  w6  = (w30+w6);
  /* #350: @8 = sq(@8) */
  w8 = casadi_sq( w8 );
  /* #351: @9 = (@9+@8) */
  w9 += w8;
  /* #352: @6 = (@6/@9) */
  w6 /= w9;
  /* #353: @5 = (@5*@6) */
  w5 *= w6;
  /* #354: @12 = (@12*@5) */
  w12 *= w5;
  /* #355: @15 = (@15*@11) */
  w15 *= w11;
  /* #356: @15 = (@30-@15) */
  w15  = (w30-w15);
  /* #357: @16 = sq(@16) */
  w16 = casadi_sq( w16 );
  /* #358: @17 = (@17+@16) */
  w17 += w16;
  /* #359: @15 = (@15/@17) */
  w15 /= w17;
  /* #360: @14 = (@14*@15) */
  w14 *= w15;
  /* #361: @12 = (@12+@14) */
  w12 += w14;
  /* #362: @1 = (@1*@12) */
  w1 *= w12;
  /* #363: @1 = (@1-@11) */
  w1 -= w11;
  /* #364: @13 = (@13*@5) */
  w13 *= w5;
  /* #365: @20 = (@20*@14) */
  w20 *= w14;
  /* #366: @13 = (@13-@20) */
  w13 -= w20;
  /* #367: @7 = (@7*@13) */
  w7 *= w13;
  /* #368: @47 = vertcat(@3, @18, @39, @30, @1, @11, @7) */
  rr=w47;
  *rr++ = w3;
  *rr++ = w18;
  *rr++ = w30;
  *rr++ = w1;
  *rr++ = w11;
  *rr++ = w7;
  /* #369: @46 = (@46+@47) */
  for (i=0, rr=w46, cs=w47; i<6; ++i) (*rr++) += (*cs++);
  /* #370: output[2][0] = @46 */
  casadi_copy(w46, 6, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Dynamic_Bicycle_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Dynamic_Bicycle_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Dynamic_Bicycle_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Dynamic_Bicycle_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Dynamic_Bicycle_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Dynamic_Bicycle_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Dynamic_Bicycle_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void Dynamic_Bicycle_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Dynamic_Bicycle_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int Dynamic_Bicycle_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real Dynamic_Bicycle_expl_vde_forw_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Dynamic_Bicycle_expl_vde_forw_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Dynamic_Bicycle_expl_vde_forw_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Dynamic_Bicycle_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    case 2: return casadi_s2;
    case 3: return casadi_s4;
    case 4: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Dynamic_Bicycle_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s6;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Dynamic_Bicycle_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12;
  if (sz_res) *sz_res = 10;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 153;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
