/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Dynamic_Bicycle_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[8] = {8, 1, 0, 4, 4, 5, 6, 7};

/* Dynamic_Bicycle_expl_vde_adj:(i0[7],i1[7],i2,i3[])->(o0[8x1,4nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, *w2=w+2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18;
  /* #0: @0 = -6.918 */
  w0 = -6.9180000000000001e+00;
  /* #1: @1 = 0.359195 */
  w1 = 3.5919540229885061e-01;
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 7, w2);
  /* #3: {@3, @4, NULL, @5, @6, @7, @8} = vertsplit(@2) */
  w3 = w2[0];
  w4 = w2[1];
  w5 = w2[3];
  w6 = w2[4];
  w7 = w2[5];
  w8 = w2[6];
  /* #4: @1 = (@1*@6) */
  w1 *= w6;
  /* #5: @9 = 0.199 */
  w9 = 1.9900000000000001e-01;
  /* #6: @10 = 11.976 */
  w10 = 1.1976047904191615e+01;
  /* #7: @10 = (@10*@8) */
  w10 *= w8;
  /* #8: @9 = (@9*@10) */
  w9 *= w10;
  /* #9: @9 = (@1-@9) */
  w9  = (w1-w9);
  /* #10: @0 = (@0*@9) */
  w0 *= w9;
  /* #11: @9 = 1 */
  w9 = 1.;
  /* #12: @8 = input[0][4] */
  w8 = arg[0] ? arg[0][4] : 0;
  /* #13: @11 = 0.199 */
  w11 = 1.9900000000000001e-01;
  /* #14: @12 = input[0][6] */
  w12 = arg[0] ? arg[0][6] : 0;
  /* #15: @13 = (@11*@12) */
  w13  = (w11*w12);
  /* #16: @13 = (@8-@13) */
  w13  = (w8-w13);
  /* #17: @13 = sq(@13) */
  w13 = casadi_sq( w13 );
  /* #18: @9 = (@9+@13) */
  w9 += w13;
  /* #19: @0 = (@0/@9) */
  w0 /= w9;
  /* #20: @9 = -6.932 */
  w9 = -6.9320000000000004e+00;
  /* #21: @13 = 0.205 */
  w13 = 2.0499999999999999e-01;
  /* #22: @13 = (@13*@10) */
  w13 *= w10;
  /* #23: @10 = input[2][0] */
  w10 = arg[2] ? arg[2][0] : 0;
  /* #24: @14 = cos(@10) */
  w14 = cos( w10 );
  /* #25: @14 = (@14*@1) */
  w14 *= w1;
  /* #26: @13 = (@13+@14) */
  w13 += w14;
  /* #27: @13 = (@9*@13) */
  w13  = (w9*w13);
  /* #28: @14 = 1 */
  w14 = 1.;
  /* #29: @15 = 0.205 */
  w15 = 2.0499999999999999e-01;
  /* #30: @12 = (@15*@12) */
  w12  = (w15*w12);
  /* #31: @12 = (@8+@12) */
  w12  = (w8+w12);
  /* #32: @16 = sq(@12) */
  w16 = casadi_sq( w12 );
  /* #33: @16 = (@14+@16) */
  w16  = (w14+w16);
  /* #34: @16 = (@13/@16) */
  w16  = (w13/w16);
  /* #35: @17 = (@0+@16) */
  w17  = (w0+w16);
  /* #36: @17 = (@17+@5) */
  w17 += w5;
  /* #37: @5 = input[0][5] */
  w5 = arg[0] ? arg[0][5] : 0;
  /* #38: @18 = cos(@5) */
  w18 = cos( w5 );
  /* #39: @18 = (@18*@4) */
  w18 *= w4;
  /* #40: @17 = (@17+@18) */
  w17 += w18;
  /* #41: @18 = sin(@5) */
  w18 = sin( w5 );
  /* #42: @18 = (@18*@3) */
  w18 *= w3;
  /* #43: @17 = (@17-@18) */
  w17 -= w18;
  /* #44: output[0][0] = @17 */
  if (res[0]) res[0][0] = w17;
  /* #45: @17 = cos(@5) */
  w17 = cos( w5 );
  /* #46: @17 = (@17*@4) */
  w17 *= w4;
  /* #47: @18 = sin(@5) */
  w18 = sin( w5 );
  /* #48: @4 = (@8*@4) */
  w4  = (w8*w4);
  /* #49: @18 = (@18*@4) */
  w18 *= w4;
  /* #50: @17 = (@17-@18) */
  w17 -= w18;
  /* #51: @18 = cos(@5) */
  w18 = cos( w5 );
  /* #52: @8 = (@8*@3) */
  w8 *= w3;
  /* #53: @18 = (@18*@8) */
  w18 *= w8;
  /* #54: @17 = (@17-@18) */
  w17 -= w18;
  /* #55: @5 = sin(@5) */
  w5 = sin( w5 );
  /* #56: @5 = (@5*@3) */
  w5 *= w3;
  /* #57: @17 = (@17-@5) */
  w17 -= w5;
  /* #58: output[0][1] = @17 */
  if (res[0]) res[0][1] = w17;
  /* #59: @7 = (@7-@6) */
  w7 -= w6;
  /* #60: @11 = (@11*@0) */
  w11 *= w0;
  /* #61: @7 = (@7-@11) */
  w7 -= w11;
  /* #62: @15 = (@15*@16) */
  w15 *= w16;
  /* #63: @7 = (@7+@15) */
  w7 += w15;
  /* #64: output[0][2] = @7 */
  if (res[0]) res[0][2] = w7;
  /* #65: @13 = (-@13) */
  w13 = (- w13 );
  /* #66: @7 = sin(@10) */
  w7 = sin( w10 );
  /* #67: @12 = atan2(@12,@14) */
  w12  = atan2(w12,w14);
  /* #68: @12 = (@12-@10) */
  w12 -= w10;
  /* #69: @9 = (@9*@12) */
  w9 *= w12;
  /* #70: @9 = (@9*@1) */
  w9 *= w1;
  /* #71: @7 = (@7*@9) */
  w7 *= w9;
  /* #72: @13 = (@13-@7) */
  w13 -= w7;
  /* #73: output[0][3] = @13 */
  if (res[0]) res[0][3] = w13;
  return 0;
}

CASADI_SYMBOL_EXPORT int Dynamic_Bicycle_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Dynamic_Bicycle_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Dynamic_Bicycle_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Dynamic_Bicycle_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Dynamic_Bicycle_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Dynamic_Bicycle_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Dynamic_Bicycle_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void Dynamic_Bicycle_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Dynamic_Bicycle_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Dynamic_Bicycle_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Dynamic_Bicycle_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Dynamic_Bicycle_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Dynamic_Bicycle_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Dynamic_Bicycle_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Dynamic_Bicycle_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Dynamic_Bicycle_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 25;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
