/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Dynamic_Bicycle_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[8] = {8, 1, 0, 4, 4, 5, 6, 7};

/* Dynamic_Bicycle_expl_vde_adj:(i0[7],i1[7],i2,i3[])->(o0[8x1,4nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5, *w6=w+6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18;
  /* #0: @0 = 2 */
  w0 = 2.;
  /* #1: @1 = 4 */
  w1 = 4.;
  /* #2: @2 = input[0][4] */
  w2 = arg[0] ? arg[0][4] : 0;
  /* #3: @3 = 0.199 */
  w3 = 1.9900000000000001e-01;
  /* #4: @4 = input[0][6] */
  w4 = arg[0] ? arg[0][6] : 0;
  /* #5: @5 = (@3*@4) */
  w5  = (w3*w4);
  /* #6: @5 = (@2-@5) */
  w5  = (w2-w5);
  /* #7: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #8: @1 = (@1+@5) */
  w1 += w5;
  /* #9: @0 = (@0/@1) */
  w0 /= w1;
  /* #10: @1 = -6.918 */
  w1 = -6.9180000000000001e+00;
  /* #11: @5 = 0.359195 */
  w5 = 3.5919540229885061e-01;
  /* #12: @6 = input[1][0] */
  casadi_copy(arg[1], 7, w6);
  /* #13: {@7, @8, NULL, @9, @10, @11, @12} = vertsplit(@6) */
  w7 = w6[0];
  w8 = w6[1];
  w9 = w6[3];
  w10 = w6[4];
  w11 = w6[5];
  w12 = w6[6];
  /* #14: @5 = (@5*@10) */
  w5 *= w10;
  /* #15: @13 = 0.199 */
  w13 = 1.9900000000000001e-01;
  /* #16: @14 = 11.976 */
  w14 = 1.1976047904191615e+01;
  /* #17: @14 = (@14*@12) */
  w14 *= w12;
  /* #18: @13 = (@13*@14) */
  w13 *= w14;
  /* #19: @13 = (@5-@13) */
  w13  = (w5-w13);
  /* #20: @1 = (@1*@13) */
  w1 *= w13;
  /* #21: @0 = (@0*@1) */
  w0 *= w1;
  /* #22: @1 = 2 */
  w1 = 2.;
  /* #23: @13 = 4 */
  w13 = 4.;
  /* #24: @12 = 0.205 */
  w12 = 2.0499999999999999e-01;
  /* #25: @4 = (@12*@4) */
  w4  = (w12*w4);
  /* #26: @4 = (@2+@4) */
  w4  = (w2+w4);
  /* #27: @15 = sq(@4) */
  w15 = casadi_sq( w4 );
  /* #28: @13 = (@13+@15) */
  w13 += w15;
  /* #29: @13 = (@1/@13) */
  w13  = (w1/w13);
  /* #30: @15 = -6.932 */
  w15 = -6.9320000000000004e+00;
  /* #31: @16 = 0.205 */
  w16 = 2.0499999999999999e-01;
  /* #32: @16 = (@16*@14) */
  w16 *= w14;
  /* #33: @14 = input[2][0] */
  w14 = arg[2] ? arg[2][0] : 0;
  /* #34: @17 = cos(@14) */
  w17 = cos( w14 );
  /* #35: @17 = (@17*@5) */
  w17 *= w5;
  /* #36: @16 = (@16+@17) */
  w16 += w17;
  /* #37: @16 = (@15*@16) */
  w16  = (w15*w16);
  /* #38: @13 = (@13*@16) */
  w13 *= w16;
  /* #39: @17 = (@0+@13) */
  w17  = (w0+w13);
  /* #40: @17 = (@17+@9) */
  w17 += w9;
  /* #41: @9 = input[0][5] */
  w9 = arg[0] ? arg[0][5] : 0;
  /* #42: @18 = cos(@9) */
  w18 = cos( w9 );
  /* #43: @18 = (@18*@8) */
  w18 *= w8;
  /* #44: @17 = (@17+@18) */
  w17 += w18;
  /* #45: @18 = sin(@9) */
  w18 = sin( w9 );
  /* #46: @18 = (@18*@7) */
  w18 *= w7;
  /* #47: @17 = (@17-@18) */
  w17 -= w18;
  /* #48: output[0][0] = @17 */
  if (res[0]) res[0][0] = w17;
  /* #49: @17 = cos(@9) */
  w17 = cos( w9 );
  /* #50: @18 = (2.*@8) */
  w18 = (2.* w8 );
  /* #51: @17 = (@17*@18) */
  w17 *= w18;
  /* #52: @18 = sin(@9) */
  w18 = sin( w9 );
  /* #53: @8 = (@2*@8) */
  w8  = (w2*w8);
  /* #54: @18 = (@18*@8) */
  w18 *= w8;
  /* #55: @17 = (@17-@18) */
  w17 -= w18;
  /* #56: @18 = cos(@9) */
  w18 = cos( w9 );
  /* #57: @2 = (@2*@7) */
  w2 *= w7;
  /* #58: @18 = (@18*@2) */
  w18 *= w2;
  /* #59: @17 = (@17-@18) */
  w17 -= w18;
  /* #60: @9 = sin(@9) */
  w9 = sin( w9 );
  /* #61: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #62: @9 = (@9*@7) */
  w9 *= w7;
  /* #63: @17 = (@17-@9) */
  w17 -= w9;
  /* #64: output[0][1] = @17 */
  if (res[0]) res[0][1] = w17;
  /* #65: @3 = (@3*@0) */
  w3 *= w0;
  /* #66: @11 = (@11-@3) */
  w11 -= w3;
  /* #67: @12 = (@12*@13) */
  w12 *= w13;
  /* #68: @11 = (@11+@12) */
  w11 += w12;
  /* #69: @12 = -2 */
  w12 = -2.;
  /* #70: @12 = (@12*@10) */
  w12 *= w10;
  /* #71: @11 = (@11+@12) */
  w11 += w12;
  /* #72: output[0][2] = @11 */
  if (res[0]) res[0][2] = w11;
  /* #73: @16 = (-@16) */
  w16 = (- w16 );
  /* #74: @11 = sin(@14) */
  w11 = sin( w14 );
  /* #75: @4 = atan2(@4,@1) */
  w4  = atan2(w4,w1);
  /* #76: @4 = (@4-@14) */
  w4 -= w14;
  /* #77: @15 = (@15*@4) */
  w15 *= w4;
  /* #78: @15 = (@15*@5) */
  w15 *= w5;
  /* #79: @11 = (@11*@15) */
  w11 *= w15;
  /* #80: @16 = (@16-@11) */
  w16 -= w11;
  /* #81: output[0][3] = @16 */
  if (res[0]) res[0][3] = w16;
  return 0;
}

CASADI_SYMBOL_EXPORT int Dynamic_Bicycle_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Dynamic_Bicycle_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Dynamic_Bicycle_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Dynamic_Bicycle_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Dynamic_Bicycle_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Dynamic_Bicycle_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Dynamic_Bicycle_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void Dynamic_Bicycle_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Dynamic_Bicycle_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Dynamic_Bicycle_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Dynamic_Bicycle_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Dynamic_Bicycle_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Dynamic_Bicycle_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Dynamic_Bicycle_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Dynamic_Bicycle_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Dynamic_Bicycle_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 25;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
