amcl:
  ros__parameters:
    alpha1: 1.0
    alpha2: 1.0
    alpha3: 0.05
    alpha4: 0.05
    alpha5: 0.05
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.5
    beam_skip_threshold: 0.5
    do_beamskip: true
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 0.125
    laser_max_range: 8.0
    laser_min_range: 0.15
    laser_model_type: "likelihood_field"
    max_beams: 120
    max_particles: 2000
    min_particles: 1500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.25
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: -1.0
    sigma_hit: 0.1
    tf_broadcast: true
    transform_tolerance: 0.25
    update_min_a: 0.001
    update_min_d: 0.001
    z_hit: 0.99
    z_max: 0.01
    z_rand: 0.01
    z_short: 0.05
    scan_topic: scan
    map_topic: map
    set_initial_pose: false
    always_reset_initial_pose: false
    first_map_only: false
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0

    
