controller:
  ros__parameters:
    speed_setpoint: 1.0       # m/s
    max_speed: 2.0            # m/s
    heartbeat_timeout: 0.5    # seconds
    max_steer: 0.65           # radians

    wheelbase: .404           # m

    control_method: "stanley" # controller type SELECT FROM: stanley | youla | mpc | hinf | pp

    stanley_k: 1.0              # stanley controller gain
    stanley_k_soft: 1.0         # stanley softening gain

    mpc_tf: 1.0               # time horizon [sec]
    mpc_N: 20                 # number of shooting nodes                
    mpc_nx: 7                 # number of states
    mpc_nu: 1                 # number of inputs

    pp_lookahead: 0.25         # pure pursuit lookahead dist [m]

    Youla_n_GcX: 4
    Youla_GcA: [1.8934, -1.0907, 0.4767, -0.2260, 1.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.5, 0.0]
    Youla_GcB: [8.0, 0.0, 0.0, 0.0]
    Youla_GcC: [0.5445, -1.2909, 2.0142, -1.0329]
    Youla_GcD: [0.0]
    Youla_lookahead: 0.5      # m

    hinf_n_GcX: 6
    hinf_GcA: [3.9338, -3.0837, 1.2084, -0.4758, 0.3034, -0.0045,
               2.0000,       0,      0,       0,      0,       0,
                    0,  2.0000,      0,       0,      0,       0,
                    0,       0, 1.0000,       0,      0,       0,
                    0,       0,      0,  0.2500,      0,       0,
                    0,       0,      0,       0, 0.0078,       0]
    hinf_GcB: [4.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    hinf_GcC: [0.2455, -0.4171, 0.2583, -0.1333, 0.0755, 1.6585]
    hinf_GcD: [0.0]
    hinf_lookahead: 0.5        # m

    waypoints: "waypoints.json"             # json title of waypoints

    

