controller:
  ros__parameters:
    speed_setpoint: 1.0       # m/s
    max_speed: 2.0            # m/s
    max_accel: 1.0            # m/s/s
    heartbeat_timeout: 0.5    # seconds
    max_steer: 0.65           # radians

    wheelbase: .404           # m

    control_method: "open_chirp" # controller type SELECT FROM: stanley | youla | mpc | hinf | pp | open_chirp

    stanley_k: 1.0              # stanley controller gain
    stanley_k_soft: 1.0         # stanley softening gain

    mpc_tf: 1.0               # time horizon [sec]
    mpc_N: 20                 # number of shooting nodes                
    mpc_nx: 7                 # number of states
    mpc_nu: 1                 # number of inputs

    pp_lookahead: 0.5         # pure pursuit lookahead dist [m]

    Youla_n_GcX: 4
    Youla_GcA: [1.8934, -1.0907, 0.4767, -0.2260,
                1.0,        0.0,    0.0,    0.0,
                0.0,        0.5,    0.0,    0.0,
                0.0,        0.0,    0.5,    0.0]
    Youla_GcB: [8.0, 0.0, 0.0, 0.0]
    Youla_GcC: [0.5445, -1.2909, 2.0142, -1.0329]
    Youla_GcD: [0.0]
    Youla_lookahead: 0.5      # m

    hinf_n_GcX: 6
    hinf_GcA: [3.1604, -1.7606, 0.7826, -0.2085, 0.0653, -0.0004,
               2.0000,     0.0,    0.0,     0.0,    0.0,     0.0,
                  0.0,  1.0000,    0.0,     0.0,    0.0,     0.0,
                  0.0,     0.0, 0.5000,     0.0,    0.0,     0.0,
                  0.0,     0.0,    0.0,  0.0625,    0.0,     0.0,
                  0.0,     0.0,    0.0,     0.0, 0.0002,     0.0]
    hinf_GcB: [16.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    hinf_GcC: [0.901, -0.1636, 0.2208, -0.2615, 0.9054, 30.0826]
    hinf_GcD: [0.0556]
    hinf_lookahead: 2.0        # m

    open_chirp_start_frequency_hz: 0.0
    open_chirp_end_frequency_hz: 4.0
    open_chirp_start_amplitude_rad: 0.5
    open_chirp_end_amplitude_rad: 0.25
    open_chirp_duration_s: 4.0
    open_chirp_settling_time_s: 1.0

    waypoints: "waypoints.json"             # json title of waypoints

    

